### ISSUE TITLE
About extensions to the framework

### ISSUE THREAD

**Issue by lyb88999** [CyberDataLab/nebula#16]
Hello, from the fedstellar project to nebula now, I think you are a very good developer, and my current research direction is to conduct federated learning training and verification on satellites. I would like to ask if it is possible to extend our framework to realize federated learning on satellites?

**Comment by enriquetomasmb** [comment]
Hi @lyb88999. Thanks! I hope that you find the platform interesting and useful. Regarding your question, I think the platform perfectly suits your use case. Feel free to fork and adapt it based on your interests. Remember to cite the work, and that's all!

We would like to hear about your progress. You could create an Issue with the label "work in progress" to report your advances in the use case.
